name: sub
description: A package to parse subtitle files like SRT and VTT.
version: 1.0.0
license: MIT
repository: https://github.com/abbashosseinii/sub

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
